import { Fragment, useEffect, useMemo, useRef, useState } from "react";
import { parseUnifiedDiff, type DiffFile, type DiffLine } from "../diff";
import { useStore } from "../store";
import type { AddReviewCommentInput, AgentModelCatalog, DiffSide, ReviewComment, Task } from "../types";

interface Anchor { filePath: string; lineNumber: number | null; lineEndNumber: number | null; side: DiffSide | null; }
const commentsAt = (comments: ReviewComment[], anchor: Anchor) => comments.filter((comment) => comment.filePath === anchor.filePath && comment.lineNumber === anchor.lineNumber && comment.side === anchor.side);
const filePath = (file: DiffFile) => file.newPath ?? file.oldPath ?? file.displayPath;
function anchorForLine(file: DiffFile, line: DiffLine, side: DiffSide): Anchor | null { const lineNumber = side === "old" ? line.oldLineNumber : line.newLineNumber; return lineNumber === null ? null : { filePath: filePath(file), lineNumber, lineEndNumber: null, side }; }

function CommentThread({ comments, onResolve, onAssign, catalogs }: { comments: ReviewComment[]; onResolve: (id: string) => Promise<void>; onAssign: (comment: ReviewComment, agentId: string | null, model: string | null) => Promise<void>; catalogs: AgentModelCatalog[] }) {
  if (!comments.length) return null;
  return <div className="review-comment-thread">{comments.map((comment) => <article className={`review-comment${comment.resolved ? " resolved" : ""}`} key={comment.id}><div><span>{comment.resolved ? "Resolved" : "Review comment"}</span><time>{new Date(comment.createdAt).toLocaleString()}</time></div><p>{comment.body}</p>{!comment.resolved && <div className="review-comment-assignment"><label>Agent <select value={comment.assignedAgentId ?? ""} onChange={(event) => { const agentId = event.target.value || null; void onAssign(comment, agentId, catalogs.find((item) => item.agentId === agentId)?.selectedModel ?? null); }}><option value="">Same as task</option>{catalogs.map((catalog) => <option key={catalog.agentId} value={catalog.agentId}>{catalog.agentLabel}</option>)}</select></label>{comment.assignedAgentId && <label>Model <select value={comment.assignedModel ?? ""} onChange={(event) => void onAssign(comment, comment.assignedAgentId, event.target.value || null)}>{(catalogs.find((item) => item.agentId === comment.assignedAgentId)?.models ?? []).map((model) => <option key={model.id} value={model.id}>{model.label}</option>)}</select></label>}</div>}{!comment.resolved && <button type="button" onClick={() => void onResolve(comment.id).catch(() => undefined)}>Resolve</button>}</article>)}</div>;
}

function DiffLineRow({ file, line, comments, anchor, onComment, onResolve, onAssign, catalogs }: { file: DiffFile; line: DiffLine; comments: ReviewComment[]; anchor: Anchor | null; onComment: (anchor: Anchor, extend: boolean) => void; onResolve: (id: string) => Promise<void>; onAssign: (comment: ReviewComment, agentId: string | null, model: string | null) => Promise<void>; catalogs: AgentModelCatalog[] }) {
  const oldAnchor = anchorForLine(file, line, "old"); const newAnchor = anchorForLine(file, line, "new");
  const isInRange = (candidate: Anchor | null) => Boolean(candidate && anchor && candidate.filePath === anchor.filePath && candidate.side === anchor.side && anchor.lineNumber !== null && candidate.lineNumber !== null && candidate.lineNumber >= anchor.lineNumber && candidate.lineNumber <= (anchor.lineEndNumber ?? anchor.lineNumber));
  const anchored = [...(oldAnchor ? commentsAt(comments, oldAnchor) : []), ...(newAnchor ? commentsAt(comments, newAnchor) : [])];
  return <Fragment><div className={`diff-line diff-line--${line.kind}${isInRange(oldAnchor) || isInRange(newAnchor) ? " diff-line--in-range" : ""}`}><button type="button" className="diff-line-number" disabled={!oldAnchor} title={oldAnchor ? "Comment on old line" : undefined} onClick={(event) => oldAnchor && onComment(oldAnchor, event.shiftKey)}>{line.oldLineNumber ?? ""}</button><button type="button" className="diff-line-number" disabled={!newAnchor} title={newAnchor ? "Comment on new line" : undefined} onClick={(event) => newAnchor && onComment(newAnchor, event.shiftKey)}>{line.newLineNumber ?? ""}</button><span className="diff-line-marker">{line.kind === "addition" ? "+" : line.kind === "deletion" ? "−" : " "}</span><code>{line.content || " "}</code></div>{anchored.length > 0 && <CommentThread comments={anchored} onResolve={onResolve} onAssign={onAssign} catalogs={catalogs} />}</Fragment>;
}

function CommentComposer({ anchor, onCancel, onSubmit }: { anchor: Anchor; onCancel: () => void; onSubmit: (input: AddReviewCommentInput) => Promise<void> }) {
  const [body, setBody] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!body.trim()) return; setSaving(true); try { await onSubmit({ ...anchor, body }); onCancel(); } finally { setSaving(false); } };
  const rangeLabel = anchor.lineNumber === null ? "File comment" : anchor.lineEndNumber && anchor.lineEndNumber !== anchor.lineNumber ? `${anchor.side} lines ${anchor.lineNumber}–${anchor.lineEndNumber}` : `${anchor.side} line ${anchor.lineNumber}`;
  return <div className="review-comment-composer"><div>{rangeLabel}</div><textarea autoFocus value={body} onChange={(event) => setBody(event.target.value)} placeholder="Leave a clear, actionable comment…" /><div><button type="button" onClick={onCancel}>Cancel</button><button type="button" className="review-primary" disabled={saving || !body.trim()} onClick={() => void submit()}>{saving ? "Saving…" : "Add comment"}</button></div></div>;
}

function ReviewContent({ task }: { task: Task }) {
  const { reviewComments, addReviewComment, resolveReviewComment, assignReviewComment, agentCatalogs, setReviewStep } = useStore();
  const files = useMemo(() => parseUnifiedDiff(task.diff ?? ""), [task.diff]); const comments = reviewComments[task.id] ?? []; const [anchor, setAnchor] = useState<Anchor | null>(null);
  const additions = files.reduce((total, file) => total + file.additions, 0); const deletions = files.reduce((total, file) => total + file.deletions, 0); const unresolved = comments.filter((comment) => !comment.resolved).length;
  const chooseAnchor = (next: Anchor, extend: boolean) => setAnchor((current) => {
    if (!extend || !current || current.filePath !== next.filePath || current.side !== next.side || current.lineNumber === null || next.lineNumber === null) return next;
    const lineNumber = Math.min(current.lineNumber, next.lineNumber);
    return { ...current, lineNumber, lineEndNumber: Math.max(current.lineNumber, next.lineNumber) };
  });
  const handleAssign = (comment: ReviewComment, agentId: string | null, model: string | null) => assignReviewComment(task.id, comment.id, agentId, model, null);
  return <><div className="review-summary"><span>{files.length} {files.length === 1 ? "file" : "files"}</span><span className="review-additions">+{additions}</span><span className="review-deletions">−{deletions}</span><span>{unresolved} unresolved</span></div>{files.length === 0 ? <div className="review-empty"><strong>No changes to display</strong><span>The task completed without a cumulative diff.</span></div> : files.map((file) => { const path = filePath(file); const fileComments = comments.filter((comment) => comment.filePath === path && comment.lineNumber === null); return <details className="diff-file" open key={file.id}><summary><span className={`diff-file-status diff-file-status--${file.status}`}>{file.status}</span><code>{file.displayPath}</code>{file.status === "renamed" && <small>{file.oldPath} → {file.newPath}</small>}<span className="diff-file-totals"><b>+{file.additions}</b><i>−{file.deletions}</i></span></summary><div className="diff-file-toolbar"><button type="button" onClick={() => setAnchor({ filePath: path, lineNumber: null, lineEndNumber: null, side: null })}>＋ File comment</button></div>{fileComments.length > 0 && <CommentThread comments={fileComments} onResolve={(id) => resolveReviewComment(task.id, id)} onAssign={handleAssign} catalogs={agentCatalogs} />}{anchor?.filePath === path && anchor.lineNumber === null && <CommentComposer anchor={anchor} onCancel={() => setAnchor(null)} onSubmit={(input) => addReviewComment(task.id, input)} />}{file.binary ? <div className="diff-binary">Binary file changed</div> : file.hunks.map((hunk) => <section className="diff-hunk" key={hunk.id}><header>{hunk.header}</header>{hunk.lines.map((line) => { const active = anchor?.filePath === path && ((anchor.side === "old" && anchor.lineNumber === line.oldLineNumber) || (anchor.side === "new" && anchor.lineNumber === line.newLineNumber)); return <Fragment key={line.id}><DiffLineRow file={file} line={line} comments={comments} anchor={anchor} onComment={chooseAnchor} onResolve={(id) => resolveReviewComment(task.id, id)} onAssign={handleAssign} catalogs={agentCatalogs} />{active && anchor && <CommentComposer anchor={anchor} onCancel={() => setAnchor(null)} onSubmit={(input) => addReviewComment(task.id, input)} />}</Fragment>; })}</section>)}</details>; })}<footer className="review-actions"><div><strong>{unresolved ? `${unresolved} unresolved comments` : "Review ready"}</strong><span>Comments stay anchored to this task turn.</span></div><button type="button" onClick={() => setReviewStep("request_changes")}>Submit review</button><button type="button" className="review-primary" disabled={unresolved > 0} title={unresolved > 0 ? "Resolve or submit comments before confirming" : undefined} onClick={() => setReviewStep("confirm")}>Confirm</button></footer></>;
}

function VerdictStep({ kind, task }: { kind: "confirm" | "request_changes"; task: Task }) {
  const { setReviewStep, reviewTaskId, reviewComments, submitReview, confirmTask, isSubmittingReview, settings, agentCatalogs } = useStore(); const [reviewerNote, setReviewerNote] = useState(""); const [merge, setMerge] = useState(settings?.mergeOnConfirm ?? false); const [requestAgent, setRequestAgent] = useState(task.agentId ?? settings?.defaultAgent ?? "codex"); const catalog = agentCatalogs.find((item) => item.agentId === requestAgent); const [requestModel, setRequestModel] = useState(catalog?.selectedModel ?? "");
  useEffect(() => { if (!requestModel && catalog) setRequestModel(catalog.selectedModel); }, [catalog, requestModel]);
  const unresolved = reviewTaskId ? (reviewComments[reviewTaskId] ?? []).filter((comment) => !comment.resolved) : []; const submittingReview = kind === "request_changes"; const canSubmit = submittingReview ? unresolved.length > 0 || Boolean(reviewerNote.trim()) : unresolved.length === 0;
  const submit = async () => { try { if (submittingReview) await submitReview(task.id, reviewerNote, { agentId: requestAgent, model: requestModel || null, effort: null }); else await confirmTask(task.id, merge); } catch { /* Store displays the actionable error. */ } };
  return <div className="review-deferred-step"><span className="review-step-icon">{submittingReview ? "↻" : "✓"}</span><h2>{submittingReview ? "Submit review" : "Confirm task"}</h2><p>{submittingReview ? "Feedback is queued as a follow-up message in this task's conversation. The task stays ready-to-run until you start it." : "Tanoor will commit the reviewed work, remove its worktree, and mark the task approved."}</p>{submittingReview ? <><div className="review-agent-selection"><label>Default agent for unassigned feedback <select value={requestAgent} onChange={(event) => { const next = event.target.value; setRequestAgent(next); setRequestModel(agentCatalogs.find((item) => item.agentId === next)?.selectedModel ?? ""); }}>{agentCatalogs.map((item) => <option key={item.agentId} value={item.agentId}>{item.agentLabel}</option>)}</select></label>{catalog && <label>Model <select value={requestModel} onChange={(event) => setRequestModel(event.target.value)}>{catalog.models.map((model) => <option key={model.id} value={model.id}>{model.label}</option>)}</select></label>}</div><label className="review-verdict-field"><span>Additional reviewer note <small>optional when comments are unresolved</small></span><textarea value={reviewerNote} onChange={(event) => setReviewerNote(event.target.value)} placeholder="Add context that is not tied to a specific diff line…" /></label></> : <label className="review-merge-option"><input type="checkbox" checked={merge} onChange={(event) => setMerge(event.target.checked)} /><span><strong>Merge into the current project branch</strong><small>Off by default. When off, the approved commit remains on <code>{task.branchName}</code>.</small></span></label>}<div className="review-boundary-note">{submittingReview ? "Comments use their per-comment assignment; unassigned feedback uses the selected agent. Each agent group runs in its own turn." : merge ? "A merge conflict is aborted automatically; the task branch and worktree remain available for retry." : "The task branch is preserved after worktree cleanup so you can merge or inspect it later."}</div><div className="review-deferred-actions"><button type="button" disabled={isSubmittingReview} onClick={() => setReviewStep("review")}>Back to review</button><button type="button" className="review-primary" disabled={isSubmittingReview || !canSubmit} onClick={() => void submit()}>{isSubmittingReview ? (submittingReview ? "Submitting…" : "Confirming…") : (submittingReview ? "Submit review" : "Confirm task")}</button></div></div>;
}

function EditorButton({ task }: { task: Task }) { const { editors, openInEditor } = useStore(); const [open, setOpen] = useState(false); const [focused, setFocused] = useState(0); const listRef = useRef<HTMLDivElement>(null); const select = (id: string) => { setOpen(false); void openInEditor(task.id, id).catch(() => undefined); }; const move = (direction: 1 | -1) => { const next = (focused + direction + editors.length) % editors.length; setFocused(next); requestAnimationFrame(() => listRef.current?.querySelectorAll<HTMLButtonElement>("button")[next]?.focus()); }; return <div className="editor-launcher"><button className="quiet-button" type="button" disabled={!task.worktreePath || !editors.length} title={!task.worktreePath ? "This task has no worktree yet — run it first" : !editors.length ? "No supported editor found" : "Open worktree in editor"} onClick={() => { if (editors.length === 1) select(editors[0].id); else { setFocused(0); setOpen((value) => !value); requestAnimationFrame(() => listRef.current?.querySelector<HTMLButtonElement>("button")?.focus()); } }}>Open in editor</button>{open && editors.length > 1 && <div ref={listRef} className="project-dropdown editor-dropdown" role="listbox" onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); move(1); } else if (event.key === "ArrowUp") { event.preventDefault(); move(-1); } else if (event.key === "Enter" || event.key === " ") { event.preventDefault(); select(editors[focused].id); } else if (event.key === "Escape") { event.preventDefault(); setOpen(false); } }}>{editors.map((editor, index) => <button key={editor.id} className="project-dropdown-item" type="button" role="option" aria-selected={index === focused} tabIndex={index === focused ? 0 : -1} onFocus={() => setFocused(index)} onClick={() => select(editor.id)}><span>{editor.label}</span><small>{editor.command}</small></button>)}</div>}</div>; }

export function ReviewScreen({ task }: { task: Task }) { const { reviewTaskId, reviewStep, closeReview, isLoadingReview, error, clearError } = useStore(); if (reviewTaskId !== task.id) return null; return <section className="review-screen" aria-label={`Review ${task.title}`}><header className="review-header"><div><span>Task review</span><h1>{task.title}</h1></div><div className="review-header-actions"><button type="button" className="quiet-button" onClick={closeReview}>← Back to task</button><EditorButton task={task} />{task.branchName && <code className="review-branch-chip">{task.branchName}</code>}</div></header>{error && <div className="review-dialog-error" role="alert"><span>{error}</span><button type="button" onClick={clearError}>Dismiss</button></div>}<div className="review-body">{isLoadingReview ? <div className="review-loading"><span className="loading-spinner" /> Loading review</div> : reviewStep === "review" ? <ReviewContent task={task} /> : <VerdictStep kind={reviewStep} task={task} />}</div></section>; }
